import type { BlogPostMeta } from "./types"

export const blogPostsMeta: BlogPostMeta[] = [
  {
    slug: "top-5-atv-maintenance-tips",
    title: "Top 5 Tips For Maintaining Your ATV",
    metaTitle: "Top 5 ATV Maintenance Tips | Subhan Enterprises",
    metaDescription:
      "Keep your quad bike running at peak performance with these essential ATV maintenance tips from Pakistan's premium dealer, Subhan Enterprises.",
    excerpt: "Keep your quad bike in top condition with these essential maintenance tips every Pakistani rider should know.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-04-10",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["maintenance", "ATV care", "quad bike"],
    relatedProductSlugs: ["engine-oil", "air-filter", "brake-pads"],
  },
  {
    slug: "best-atvs-off-road-adventures-pakistan",
    title: "Best ATVs For Off-Road Adventures in Pakistan",
    metaTitle: "Best ATVs for Off-Road Adventures in Pakistan | Subhan Enterprises",
    metaDescription:
      "Discover the best quad bikes for Pakistan's diverse terrain — from northern mountain trails to southern deserts. Expert picks from Subhan Enterprises.",
    excerpt: "Explore our top picks for the ultimate off-road thrill across Pakistan's diverse landscapes.",
    featuredImage: "/atvs/blog-offroad.png",
    category: "adventures",
    publishedAt: "2025-04-22",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["off-road", "adventures", "quad bikes"],
    relatedProductSlugs: ["raptor-700r", "kawasaki-brute-force", "cfmoto-520l"],
  },
  {
    slug: "atv-safety-gear-essentials",
    title: "ATV Safety Gear: What You Need Before Every Ride",
    metaTitle: "Essential ATV Safety Gear Guide | Subhan Enterprises",
    metaDescription:
      "Complete guide to ATV safety gear — helmets, gloves, goggles, body armor and more. Stay protected on every ride with Subhan Enterprises.",
    excerpt: "Stay safe on every ride with the right gear and equipment every responsible rider needs.",
    featuredImage: "/atvs/blog-safety.png",
    category: "safety",
    publishedAt: "2025-05-05",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["safety", "gear", "helmets"],
    relatedProductSlugs: ["off-road-helmet", "riding-goggles", "chest-protector"],
  },
  {
    slug: "choosing-first-quad-bike-pakistan",
    title: "How to Choose Your First Quad Bike in Pakistan",
    metaTitle: "First Quad Bike Buying Guide Pakistan | Subhan Enterprises",
    metaDescription:
      "First-time ATV buyer? Learn how to choose the right quad bike for your budget, terrain and experience level in Pakistan.",
    excerpt: "A complete beginner's guide to picking the perfect first ATV for Pakistani terrain and budgets.",
    featuredImage: "/atvs/linhai-lh400.png",
    category: "buying-guide",
    publishedAt: "2025-05-18",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["buying guide", "beginners", "first ATV"],
    relatedProductSlugs: ["linhai-lh400", "cfmoto-520l", "honda-trx420"],
  },
  {
    slug: "cfmoto-vs-can-am-comparison",
    title: "CFMOTO vs Can-Am: Which ATV Is Right For You?",
    metaTitle: "CFMOTO vs Can-Am ATV Comparison | Subhan Enterprises",
    metaDescription:
      "Detailed comparison of CFMOTO and Can-Am ATVs for the Pakistani market — performance, price, features and value.",
    excerpt: "We compare two popular ATV brands to help you decide which quad bike suits your riding style.",
    featuredImage: "/atvs/can-am-outlander.png",
    category: "buying-guide",
    publishedAt: "2025-06-02",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["CFMOTO", "Can-Am", "comparison"],
    relatedProductSlugs: ["cfmoto-520l", "can-am-outlander", "cfmoto-cforce-625"],
  },
  {
    slug: "atv-financing-options-pakistan",
    title: "ATV Financing & Installment Options in Pakistan",
    metaTitle: "ATV Financing Options Pakistan | Subhan Enterprises",
    metaDescription:
      "Learn about ATV financing, installment plans and trade-in options available at Subhan Enterprises for quad bike buyers in Pakistan.",
    excerpt: "Flexible financing and installment plans make owning your dream quad bike more accessible than ever.",
    featuredImage: "/atvs/hero-atv.png",
    category: "buying-guide",
    publishedAt: "2025-06-15",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["financing", "installments", "payment"],
    relatedProductSlugs: ["raptor-700r", "polaris-sportsman-570"],
  },
  {
    slug: "winter-atv-storage-guide",
    title: "How to Store Your ATV During Off-Season",
    metaTitle: "ATV Winter Storage Guide | Subhan Enterprises",
    metaDescription:
      "Protect your quad bike during Pakistan's off-season with proper storage, battery care and fluid maintenance tips.",
    excerpt: "Proper off-season storage keeps your ATV ready to ride when adventure season returns.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-07-01",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["storage", "winter care", "maintenance"],
    relatedProductSlugs: ["powersports-battery", "engine-oil", "coolant-premium"],
  },
  {
    slug: "off-road-trails-northern-pakistan",
    title: "Top Off-Road ATV Trails in Northern Pakistan",
    metaTitle: "Best ATV Trails Northern Pakistan | Subhan Enterprises",
    metaDescription:
      "Discover the best off-road ATV trails in northern Pakistan — from Murree hills to Swat valleys and beyond.",
    excerpt: "From Murree to Swat, explore Pakistan's most thrilling ATV trails for every skill level.",
    featuredImage: "/atvs/lifestyle-rider.png",
    category: "adventures",
    publishedAt: "2025-07-14",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["trails", "northern Pakistan", "adventures"],
    relatedProductSlugs: ["kawasaki-brute-force", "arctic-cat-alterra"],
  },
  {
    slug: "atv-engine-oil-guide",
    title: "Complete Guide to ATV Engine Oil & Fluids",
    metaTitle: "ATV Engine Oil Guide | Subhan Enterprises",
    metaDescription:
      "Everything you need to know about ATV engine oil, coolant and fluid maintenance for 4-stroke quad bikes.",
    excerpt: "Choosing the right engine oil and fluids is critical for long-term ATV engine health.",
    featuredImage: "/products/oil.png",
    category: "maintenance",
    publishedAt: "2025-07-28",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["engine oil", "fluids", "maintenance"],
    relatedProductSlugs: ["engine-oil", "coolant-premium"],
  },
  {
    slug: "quad-bike-warranty-explained",
    title: "Understanding Your Quad Bike Warranty",
    metaTitle: "Quad Bike Warranty Explained | Subhan Enterprises",
    metaDescription:
      "What does a 1-year ATV warranty cover? Learn about warranty terms, claims and after-sales support at Subhan Enterprises.",
    excerpt: "Know exactly what your 1-year warranty covers and how to make the most of after-sales support.",
    featuredImage: "/atvs/raptor-700r.png",
    category: "news",
    publishedAt: "2025-08-05",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["warranty", "support", "after-sales"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l"],
  },
  {
    slug: "farm-atv-vs-sport-atv",
    title: "Farm Utility ATV vs Sport ATV: Which Do You Need?",
    metaTitle: "Utility vs Sport ATV Guide | Subhan Enterprises",
    metaDescription:
      "Utility or sport ATV? Compare use cases, features and top models for farm work versus recreational riding in Pakistan.",
    excerpt: "Understand the key differences between utility and sport ATVs to match your riding needs.",
    featuredImage: "/atvs/cfmoto-520l.png",
    category: "buying-guide",
    publishedAt: "2025-08-12",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["utility ATV", "sport ATV", "comparison"],
    relatedProductSlugs: ["honda-trx420", "raptor-700r", "polaris-sportsman-570"],
  },
  {
    slug: "atv-tire-selection-guide",
    title: "How to Choose the Right ATV Tires",
    metaTitle: "ATV Tire Selection Guide | Subhan Enterprises",
    metaDescription:
      "Knobby, all-terrain or mud tires? Complete guide to choosing ATV tires for Pakistani terrain and riding conditions.",
    excerpt: "The right tires transform your ride — learn how to pick the perfect set for your terrain.",
    featuredImage: "/products/tire.png",
    category: "maintenance",
    publishedAt: "2025-08-20",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["tires", "parts", "maintenance"],
    relatedProductSlugs: ["off-road-tire"],
  },
  {
    slug: "night-riding-atv-light-setup",
    title: "Night Riding: Essential ATV Light Setup Guide",
    metaTitle: "ATV Night Riding Light Setup | Subhan Enterprises",
    metaDescription:
      "Plan your ATV night riding setup with LED light bars, wiring tips and safety considerations for Pakistani riders.",
    excerpt: "Illuminate the trail safely with the right LED lighting setup for night adventures.",
    featuredImage: "/products/lightbar.png",
    category: "safety",
    publishedAt: "2025-08-28",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["lighting", "night riding", "accessories"],
    relatedProductSlugs: ["led-light-bar"],
  },
  {
    slug: "atv-break-in-period-guide",
    title: "ATV Break-In Period: What Every New Owner Must Know",
    metaTitle: "ATV Break-In Period Guide | Subhan Enterprises",
    metaDescription:
      "Protect your new quad bike investment by following proper break-in procedures for engine, brakes and transmission.",
    excerpt: "The first 20 hours on your new ATV are critical — follow these break-in guidelines.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-09-05",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["break-in", "new ATV", "maintenance"],
    relatedProductSlugs: ["engine-oil", "spark-plugs-set"],
  },
  {
    slug: "subhan-enterprises-buying-guide",
    title: "The Complete Subhan Enterprises Buying Guide 2025",
    metaTitle: "Complete ATV Buying Guide 2025 | Subhan Enterprises",
    metaDescription:
      "Your complete 2025 guide to buying an ATV from Subhan Enterprises — models, pricing, delivery, warranty and support.",
    excerpt: "Everything you need to know about buying your next quad bike from Pakistan's premium ATV dealer.",
    featuredImage: "/atvs/hero-atv.png",
    imageAlt: "Subhan Enterprises ATV showroom — complete buying guide Pakistan 2025",
    category: "news",
    publishedAt: "2025-09-15",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["buying guide", "2025", "Subhan Enterprises"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l", "can-am-outlander"],
  },
  {
    slug: "atv-price-guide-pakistan-2025",
    title: "ATV Price Guide Pakistan 2025 — What Does a Quad Bike Cost?",
    metaTitle: "ATV Price in Pakistan 2025 | Quad Bike Price Guide | Subhan Enterprises",
    metaDescription:
      "Complete ATV and quad bike price guide for Pakistan 2025. Entry-level, mid-range and premium models compared — what you get at every budget from Subhan Enterprises.",
    excerpt: "From entry-level to premium, here is exactly what ATVs cost in Pakistan in 2025 and what drives the price difference.",
    featuredImage: "/atvs/hero-atv.png",
    imageAlt: "ATV quad bike price guide Pakistan 2025 — Subhan Enterprises",
    category: "buying-guide",
    publishedAt: "2025-09-20",
    updatedAt: "2025-09-20",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["ATV price", "quad bike price", "Pakistan", "buying guide"],
    relatedProductSlugs: ["linhai-lh400", "cfmoto-520l", "raptor-700r", "can-am-outlander"],
    relatedArticleSlugs: ["choosing-first-quad-bike-pakistan", "cfmoto-vs-can-am-comparison", "subhan-enterprises-buying-guide"],
  },
  {
    slug: "dirt-bike-vs-atv-pakistan",
    title: "Dirt Bike vs ATV in Pakistan — Which is Right for You?",
    metaTitle: "Dirt Bike vs ATV Pakistan — Full Comparison Guide | Subhan Enterprises",
    metaDescription:
      "Dirt bike or ATV? Compare both for Pakistani terrain, riding style, safety, and budget. Honest guide from Pakistan's leading ATV dealer, Subhan Enterprises.",
    excerpt: "An honest comparison of dirt bikes and ATVs to help Pakistani riders choose the right off-road machine for their needs.",
    featuredImage: "/atvs/blog-offroad.png",
    imageAlt: "Dirt bike vs ATV comparison for Pakistan riders",
    category: "buying-guide",
    publishedAt: "2025-09-25",
    updatedAt: "2025-09-25",
    readTime: 11,
    author: "Subhan Enterprises Team",
    tags: ["dirt bike", "ATV", "comparison", "Pakistan"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l", "linhai-lh400"],
    relatedArticleSlugs: ["atv-price-guide-pakistan-2025", "farm-atv-pakistan-guide", "atv-vs-dirt-bike-kids-pakistan"],
  },
  {
    slug: "trail-bike-pakistan-guide",
    title: "Trail Bike Pakistan — A Complete Guide to Trail Riding",
    metaTitle: "Trail Bike Pakistan — Trail Riding Guide & Best Options | Subhan Enterprises",
    metaDescription:
      "Everything you need to know about trail bikes and trail riding in Pakistan — terrain, top models, gear and the best off-road ATVs for trail adventures.",
    excerpt: "Discover the best trail riding options in Pakistan and what makes a great trail machine for our diverse terrain.",
    featuredImage: "/atvs/lifestyle-rider.png",
    imageAlt: "Trail bike riding in Pakistan — off-road adventure guide",
    category: "adventures",
    publishedAt: "2025-09-30",
    updatedAt: "2025-09-30",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["trail bike", "trail riding", "Pakistan", "off-road"],
    relatedProductSlugs: ["cfmoto-520l", "kawasaki-brute-force", "arctic-cat-alterra"],
    relatedArticleSlugs: ["trail-riding-spots-pakistan", "off-road-trails-northern-pakistan", "best-atvs-off-road-adventures-pakistan"],
  },
  {
    slug: "off-road-riding-beginners-pakistan",
    title: "Off-Road Riding in Pakistan — A Beginner's Complete Guide",
    metaTitle: "Off-Road Riding Pakistan Beginners Guide | Subhan Enterprises",
    metaDescription:
      "New to off-road riding in Pakistan? This guide covers choosing your first ATV, essential gear, beginner-friendly trails, and safety basics for new riders.",
    excerpt: "Everything a first-time off-road rider in Pakistan needs to know — from picking a machine to your first trail adventure.",
    featuredImage: "/atvs/blog-safety.png",
    imageAlt: "Beginner off-road ATV riding guide Pakistan",
    category: "safety",
    publishedAt: "2025-10-05",
    updatedAt: "2025-10-05",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["beginners", "off-road", "Pakistan", "safety"],
    relatedProductSlugs: ["linhai-lh400", "off-road-helmet", "chest-protector", "riding-goggles"],
    relatedArticleSlugs: ["atv-safety-gear-essentials", "choosing-first-quad-bike-pakistan", "trail-riding-spots-pakistan"],
  },
  {
    slug: "quad-bike-price-pakistan",
    title: "Quad Bike Price in Pakistan 2025 — All Models Compared",
    metaTitle: "Quad Bike Price Pakistan 2025 | All Models | Subhan Enterprises",
    metaDescription:
      "Up-to-date quad bike prices in Pakistan for 2025. Compare all Subhan Enterprises models from PKR 1.35M to PKR 2.85M with full spec breakdown and value analysis.",
    excerpt: "A complete price comparison of all quad bikes available at Subhan Enterprises in Pakistan for 2025.",
    featuredImage: "/atvs/cfmoto-520l.png",
    imageAlt: "Quad bike prices Pakistan 2025 — all models compared",
    category: "buying-guide",
    publishedAt: "2025-10-08",
    updatedAt: "2025-10-08",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["quad bike price", "Pakistan", "2025", "buying guide"],
    relatedProductSlugs: ["linhai-lh400", "honda-trx420", "cfmoto-520l", "raptor-700r", "can-am-outlander", "kawasaki-brute-force"],
    relatedArticleSlugs: ["atv-price-guide-pakistan-2025", "cfmoto-vs-can-am-comparison", "farm-atv-vs-sport-atv"],
  },
  {
    slug: "best-dirt-bikes-pakistan",
    title: "Best Off-Road Bikes in Pakistan — Dirt Bikes, Trail Bikes & ATVs",
    metaTitle: "Best Off-Road Bikes Pakistan 2025 — Dirt Bikes vs ATVs | Subhan Enterprises",
    metaDescription:
      "Looking for the best off-road bike in Pakistan? Explore dirt bikes, trail bikes and ATVs — what to look for, top options, and why many riders prefer ATVs for Pakistani terrain.",
    excerpt: "A practical guide to the best off-road bikes available in Pakistan, including dirt bikes, trail bikes and ATV quad bikes.",
    featuredImage: "/atvs/blog-offroad.png",
    imageAlt: "Best off-road bikes in Pakistan — dirt bikes trail bikes and ATVs",
    category: "buying-guide",
    publishedAt: "2025-10-12",
    updatedAt: "2025-10-12",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["dirt bike", "trail bike", "off-road bike", "Pakistan"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l", "kawasaki-brute-force"],
    relatedArticleSlugs: ["dirt-bike-vs-atv-pakistan", "trail-bike-pakistan-guide", "best-atvs-off-road-adventures-pakistan"],
  },
  {
    slug: "atv-vs-dirt-bike-kids-pakistan",
    title: "Kids ATV vs Dirt Bike in Pakistan — A Parent's Guide",
    metaTitle: "Kids ATV vs Dirt Bike Pakistan — Parent's Safety Guide | Subhan Enterprises",
    metaDescription:
      "Choosing between a kids ATV and a dirt bike in Pakistan? Compare safety, age-suitability, costs and recommendations from Subhan Enterprises for responsible parents.",
    excerpt: "A parent's practical guide to choosing between a kids ATV and a dirt bike for young riders in Pakistan.",
    featuredImage: "/atvs/blog-safety.png",
    imageAlt: "Kids ATV vs dirt bike Pakistan safety guide for parents",
    category: "buying-guide",
    publishedAt: "2025-10-15",
    updatedAt: "2025-10-15",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["kids ATV", "dirt bike", "safety", "Pakistan"],
    relatedProductSlugs: ["off-road-helmet", "chest-protector", "riding-goggles"],
    relatedArticleSlugs: ["atv-safety-gear-essentials", "dirt-bike-vs-atv-pakistan", "off-road-riding-beginners-pakistan"],
  },
  {
    slug: "trail-riding-spots-pakistan",
    title: "Best Trail Riding Spots in Pakistan for ATV & Off-Road Adventures",
    metaTitle: "Best Trail Riding Spots Pakistan — ATV & Off-Road Guide | Subhan Enterprises",
    metaDescription:
      "Discover Pakistan's top trail riding destinations for ATVs and off-road bikes — from Murree to Swat, Nathia Gali to Deosai. Routes, difficulty, and gear checklist.",
    excerpt: "Pakistan has world-class trail riding terrain. Here are the best spots for ATV and off-road adventures, with practical tips.",
    featuredImage: "/atvs/lifestyle-rider.png",
    imageAlt: "Best ATV trail riding spots in Pakistan — off-road adventure guide",
    category: "adventures",
    publishedAt: "2025-10-20",
    updatedAt: "2025-10-20",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["trail riding", "Pakistan", "adventures", "off-road spots"],
    relatedProductSlugs: ["cfmoto-520l", "kawasaki-brute-force", "arctic-cat-alterra", "off-road-helmet"],
    relatedArticleSlugs: ["trail-bike-pakistan-guide", "off-road-trails-northern-pakistan", "atv-safety-gear-essentials"],
  },
  {
    slug: "farm-atv-pakistan-guide",
    title: "Farm ATV in Pakistan — Best Utility Quad Bikes for Agriculture",
    metaTitle: "Farm ATV Pakistan — Best Utility Quad Bikes for Farmers | Subhan Enterprises",
    metaDescription:
      "Considering an ATV for your farm in Pakistan? Compare utility quad bikes for agricultural use — load capacity, fuel efficiency, terrain handling and top models for Pakistani farming.",
    excerpt: "A practical guide for Pakistani farmers considering an ATV — the best utility quad bikes for agricultural work and farm management.",
    featuredImage: "/atvs/cfmoto-520l.png",
    imageAlt: "Farm utility ATV Pakistan — quad bike for agriculture",
    category: "buying-guide",
    publishedAt: "2025-10-22",
    updatedAt: "2025-10-22",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["farm ATV", "utility ATV", "agriculture", "Pakistan"],
    relatedProductSlugs: ["honda-trx420", "cfmoto-520l", "polaris-sportsman-570"],
    relatedArticleSlugs: ["farm-atv-vs-sport-atv", "atv-price-guide-pakistan-2025", "quad-bike-price-pakistan"],
  },
  {
    slug: "atv-accessories-must-have-pakistan",
    title: "Top 10 Must-Have ATV Accessories for Pakistani Riders",
    metaTitle: "Must-Have ATV Accessories Pakistan 2025 | Subhan Enterprises",
    metaDescription:
      "The 10 most essential ATV accessories for Pakistani riders in 2025 — helmets, lights, tires, and more. Shop genuine accessories at Subhan Enterprises.",
    excerpt: "Upgrade your ATV experience with these 10 essential accessories every Pakistani rider should own.",
    featuredImage: "/products/lightbar.png",
    imageAlt: "Must-have ATV accessories for Pakistani riders 2025",
    category: "maintenance",
    publishedAt: "2025-10-25",
    updatedAt: "2025-10-25",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["ATV accessories", "Pakistan", "gear", "upgrades"],
    relatedProductSlugs: ["off-road-helmet", "led-light-bar", "off-road-tire", "riding-goggles", "chest-protector"],
    relatedArticleSlugs: ["atv-safety-gear-essentials", "night-riding-atv-light-setup", "atv-tire-selection-guide"],
  },
]

