import type { BlogPostMeta } from "./types"

export const blogPostsMeta: BlogPostMeta[] = [
  {
    slug: "top-5-atv-maintenance-tips",
    title: "Top 5 Tips For Maintaining Your ATV",
    metaTitle: "Top 5 ATV Maintenance Tips | Subhan Enterprises",
    metaDescription:
      "Keep your quad bike running at peak performance with these essential ATV maintenance tips from Pakistan's premium dealer, Subhan Enterprises.",
    excerpt: "Keep your quad bike in top condition with these essential maintenance tips every Pakistani rider should know.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-04-10",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["maintenance", "ATV care", "quad bike"],
    relatedProductSlugs: ["engine-oil", "air-filter", "brake-pads"],
  },
  {
    slug: "best-atvs-off-road-adventures-pakistan",
    title: "Best ATVs For Off-Road Adventures in Pakistan",
    metaTitle: "Best ATVs for Off-Road Adventures in Pakistan | Subhan Enterprises",
    metaDescription:
      "Discover the best quad bikes for Pakistan's diverse terrain — from northern mountain trails to southern deserts. Expert picks from Subhan Enterprises.",
    excerpt: "Explore our top picks for the ultimate off-road thrill across Pakistan's diverse landscapes.",
    featuredImage: "/atvs/blog-offroad.png",
    category: "adventures",
    publishedAt: "2025-04-22",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["off-road", "adventures", "quad bikes"],
    relatedProductSlugs: ["raptor-700r", "kawasaki-brute-force", "cfmoto-520l"],
  },
  {
    slug: "atv-safety-gear-essentials",
    title: "ATV Safety Gear: What You Need Before Every Ride",
    metaTitle: "Essential ATV Safety Gear Guide | Subhan Enterprises",
    metaDescription:
      "Complete guide to ATV safety gear — helmets, gloves, goggles, body armor and more. Stay protected on every ride with Subhan Enterprises.",
    excerpt: "Stay safe on every ride with the right gear and equipment every responsible rider needs.",
    featuredImage: "/atvs/blog-safety.png",
    category: "safety",
    publishedAt: "2025-05-05",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["safety", "gear", "helmets"],
    relatedProductSlugs: ["off-road-helmet", "riding-goggles", "chest-protector"],
  },
  {
    slug: "choosing-first-quad-bike-pakistan",
    title: "How to Choose Your First Quad Bike in Pakistan",
    metaTitle: "First Quad Bike Buying Guide Pakistan | Subhan Enterprises",
    metaDescription:
      "First-time ATV buyer? Learn how to choose the right quad bike for your budget, terrain and experience level in Pakistan.",
    excerpt: "A complete beginner's guide to picking the perfect first ATV for Pakistani terrain and budgets.",
    featuredImage: "/atvs/linhai-lh400.png",
    category: "buying-guide",
    publishedAt: "2025-05-18",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["buying guide", "beginners", "first ATV"],
    relatedProductSlugs: ["linhai-lh400", "cfmoto-520l", "honda-trx420"],
  },
  {
    slug: "cfmoto-vs-can-am-comparison",
    title: "CFMOTO vs Can-Am: Which ATV Is Right For You?",
    metaTitle: "CFMOTO vs Can-Am ATV Comparison | Subhan Enterprises",
    metaDescription:
      "Detailed comparison of CFMOTO and Can-Am ATVs for the Pakistani market — performance, price, features and value.",
    excerpt: "We compare two popular ATV brands to help you decide which quad bike suits your riding style.",
    featuredImage: "/atvs/can-am-outlander.png",
    category: "buying-guide",
    publishedAt: "2025-06-02",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["CFMOTO", "Can-Am", "comparison"],
    relatedProductSlugs: ["cfmoto-520l", "can-am-outlander", "cfmoto-cforce-625"],
  },
  {
    slug: "atv-financing-options-pakistan",
    title: "ATV Financing & Installment Options in Pakistan",
    metaTitle: "ATV Financing Options Pakistan | Subhan Enterprises",
    metaDescription:
      "Learn about ATV financing, installment plans and trade-in options available at Subhan Enterprises for quad bike buyers in Pakistan.",
    excerpt: "Flexible financing and installment plans make owning your dream quad bike more accessible than ever.",
    featuredImage: "/atvs/hero-atv.png",
    category: "buying-guide",
    publishedAt: "2025-06-15",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["financing", "installments", "payment"],
    relatedProductSlugs: ["raptor-700r", "polaris-sportsman-570"],
  },
  {
    slug: "winter-atv-storage-guide",
    title: "How to Store Your ATV During Off-Season",
    metaTitle: "ATV Winter Storage Guide | Subhan Enterprises",
    metaDescription:
      "Protect your quad bike during Pakistan's off-season with proper storage, battery care and fluid maintenance tips.",
    excerpt: "Proper off-season storage keeps your ATV ready to ride when adventure season returns.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-07-01",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["storage", "winter care", "maintenance"],
    relatedProductSlugs: ["powersports-battery", "engine-oil", "coolant-premium"],
  },
  {
    slug: "off-road-trails-northern-pakistan",
    title: "Top Off-Road ATV Trails in Northern Pakistan",
    metaTitle: "Best ATV Trails Northern Pakistan | Subhan Enterprises",
    metaDescription:
      "Discover the best off-road ATV trails in northern Pakistan — from Murree hills to Swat valleys and beyond.",
    excerpt: "From Murree to Swat, explore Pakistan's most thrilling ATV trails for every skill level.",
    featuredImage: "/atvs/lifestyle-rider.png",
    category: "adventures",
    publishedAt: "2025-07-14",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["trails", "northern Pakistan", "adventures"],
    relatedProductSlugs: ["kawasaki-brute-force", "arctic-cat-alterra"],
  },
  {
    slug: "atv-engine-oil-guide",
    title: "Complete Guide to ATV Engine Oil & Fluids",
    metaTitle: "ATV Engine Oil Guide | Subhan Enterprises",
    metaDescription:
      "Everything you need to know about ATV engine oil, coolant and fluid maintenance for 4-stroke quad bikes.",
    excerpt: "Choosing the right engine oil and fluids is critical for long-term ATV engine health.",
    featuredImage: "/products/oil.png",
    category: "maintenance",
    publishedAt: "2025-07-28",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["engine oil", "fluids", "maintenance"],
    relatedProductSlugs: ["engine-oil", "coolant-premium"],
  },
  {
    slug: "quad-bike-warranty-explained",
    title: "Understanding Your Quad Bike Warranty",
    metaTitle: "Quad Bike Warranty Explained | Subhan Enterprises",
    metaDescription:
      "What does a 1-year ATV warranty cover? Learn about warranty terms, claims and after-sales support at Subhan Enterprises.",
    excerpt: "Know exactly what your 1-year warranty covers and how to make the most of after-sales support.",
    featuredImage: "/atvs/raptor-700r.png",
    category: "news",
    publishedAt: "2025-08-05",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["warranty", "support", "after-sales"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l"],
  },
  {
    slug: "farm-atv-vs-sport-atv",
    title: "Farm Utility ATV vs Sport ATV: Which Do You Need?",
    metaTitle: "Utility vs Sport ATV Guide | Subhan Enterprises",
    metaDescription:
      "Utility or sport ATV? Compare use cases, features and top models for farm work versus recreational riding in Pakistan.",
    excerpt: "Understand the key differences between utility and sport ATVs to match your riding needs.",
    featuredImage: "/atvs/cfmoto-520l.png",
    category: "buying-guide",
    publishedAt: "2025-08-12",
    readTime: 9,
    author: "Subhan Enterprises Team",
    tags: ["utility ATV", "sport ATV", "comparison"],
    relatedProductSlugs: ["honda-trx420", "raptor-700r", "polaris-sportsman-570"],
  },
  {
    slug: "atv-tire-selection-guide",
    title: "How to Choose the Right ATV Tires",
    metaTitle: "ATV Tire Selection Guide | Subhan Enterprises",
    metaDescription:
      "Knobby, all-terrain or mud tires? Complete guide to choosing ATV tires for Pakistani terrain and riding conditions.",
    excerpt: "The right tires transform your ride — learn how to pick the perfect set for your terrain.",
    featuredImage: "/products/tire.png",
    category: "maintenance",
    publishedAt: "2025-08-20",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["tires", "parts", "maintenance"],
    relatedProductSlugs: ["off-road-tire"],
  },
  {
    slug: "night-riding-atv-light-setup",
    title: "Night Riding: Essential ATV Light Setup Guide",
    metaTitle: "ATV Night Riding Light Setup | Subhan Enterprises",
    metaDescription:
      "Plan your ATV night riding setup with LED light bars, wiring tips and safety considerations for Pakistani riders.",
    excerpt: "Illuminate the trail safely with the right LED lighting setup for night adventures.",
    featuredImage: "/products/lightbar.png",
    category: "safety",
    publishedAt: "2025-08-28",
    readTime: 7,
    author: "Subhan Enterprises Team",
    tags: ["lighting", "night riding", "accessories"],
    relatedProductSlugs: ["led-light-bar"],
  },
  {
    slug: "atv-break-in-period-guide",
    title: "ATV Break-In Period: What Every New Owner Must Know",
    metaTitle: "ATV Break-In Period Guide | Subhan Enterprises",
    metaDescription:
      "Protect your new quad bike investment by following proper break-in procedures for engine, brakes and transmission.",
    excerpt: "The first 20 hours on your new ATV are critical — follow these break-in guidelines.",
    featuredImage: "/atvs/blog-maintenance.png",
    category: "maintenance",
    publishedAt: "2025-09-05",
    readTime: 8,
    author: "Subhan Enterprises Team",
    tags: ["break-in", "new ATV", "maintenance"],
    relatedProductSlugs: ["engine-oil", "spark-plugs-set"],
  },
  {
    slug: "subhan-enterprises-buying-guide",
    title: "The Complete Subhan Enterprises Buying Guide 2025",
    metaTitle: "Complete ATV Buying Guide 2025 | Subhan Enterprises",
    metaDescription:
      "Your complete 2025 guide to buying an ATV from Subhan Enterprises — models, pricing, delivery, warranty and support.",
    excerpt: "Everything you need to know about buying your next quad bike from Pakistan's premium ATV dealer.",
    featuredImage: "/atvs/hero-atv.png",
    category: "news",
    publishedAt: "2025-09-15",
    readTime: 10,
    author: "Subhan Enterprises Team",
    tags: ["buying guide", "2025", "Subhan Enterprises"],
    relatedProductSlugs: ["raptor-700r", "cfmoto-520l", "can-am-outlander"],
  },
]
